#return the number of unique elements in the array and also sort the array in place removing the duplicates
#we can use two pointers to iterate through the list and compare the elements.

def removeDuplicates(nums : list[int])-> int:
     i,j =0,1
     unique = 1
     n = len(nums)-1
     while j<=n:
          if nums[i] == nums[j]:
               j+=1
          else:
               i+=1 #increment the index of the unique element
               nums[i] = nums[j] #replace the unique element with the next element
               unique+=1
     
     return unique

#test cases generated by copilot
nums = [1, 1, 2]
print(removeDuplicates(nums), nums)  # ✅ Output: 2, nums = [1, 2, _]

nums = [0,0,1,1,1,2,2,3,3,4]
print(removeDuplicates(nums), nums)  # ✅ Output: 5, nums = [0,1,2,3,4,_,_,_,_,_]

nums = [1,2,3,4,5]
print(removeDuplicates(nums), nums)  # ✅ Output: 5, nums = [1,2,3,4,5]

nums = [1,1,1,1,1]
print(removeDuplicates(nums), nums)  # ✅ Output: 1, nums = [1,_,_,_,_]